import Link from 'next/link';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';

const guides: Record<string,{title:string;description:string;body:string[];points:string[]}> = {
 'sportsbook-odds-comparison':{title:'Sportsbook Odds Comparison',description:'Compare the same market across sportsbooks and understand why price differences matter.',body:['Sportsbooks can post different prices on the same outcome. Comparing those prices is the foundation of line shopping and is also how a mathematical arbitrage can become visible.','A comparison is only useful when the event, market, line and settlement terms actually match. InQsi treats freshness and market identity as part of the comparison rather than assuming every displayed number is interchangeable.'],points:['Match the event and market exactly','Compare current prices, not stale screenshots','Check settlement and house-rule differences','Recalculate after any price changes']},
 'what-is-sports-arbitrage':{title:'What Is Sports Arbitrage?',description:'A plain-English explanation of sports arbitrage, implied probability and execution risk.',body:['Sports arbitrage exists when prices available across outcomes imply a combined probability below 100%. In the mathematical ideal, stakes can then be allocated so the gross payout exceeds the total amount staked regardless of which covered outcome wins.','Real markets add execution risk. Prices can move, limits can differ, markets can be suspended, and books can use different settlement rules. A calculation therefore needs current, matching, confirmed quotes.'],points:['Convert every price to decimal or implied probability','Add the implied probabilities for all mutually exclusive outcomes','A total below 100% is the mathematical arbitrage condition','Verify freshness, limits and settlement before relying on the calculation']},
 'arbitrage-examples':{title:'Sports Arbitrage Examples',description:'Transparent examples showing how two-way and three-way arbitrage math works.',body:['Suppose two mutually exclusive outcomes are priced at +110 and +105. Those correspond to decimal prices of 2.10 and 2.05. Their inverse probabilities sum to about 96.39%, which is below 100% and therefore represents a mathematical arbitrage before execution considerations.','For a $1,000 total allocation, proportional staking by inverse decimal odds balances the gross payout. The same method extends to three-way markets by including all three mutually exclusive outcomes.'],points:['Example prices are illustrative, not live sportsbook quotes','Balanced staking uses each outcome’s inverse decimal price','The edge disappears if one price changes enough before execution','Three-way markets require all three outcomes to be covered']},
 'sports-betting-line-movement':{title:'Sports Betting Line Movement',description:'Understand what sportsbook line movement measures and why confirmation and timing matter.',body:['Line movement is a change in a sportsbook price or point line over time. It can reflect new information, market action, risk management or a book following the broader market. A move by itself does not prove why it happened.','Comparing multiple books and timestamps helps distinguish a broad market move from an isolated quote. InQsi uses confirmed market observations and freshness controls rather than treating every price change as equally meaningful.'],points:['Record both price and timestamp','Compare the same market across multiple books','Separate line changes from price-only changes','Do not infer a cause from movement alone']},
 'mlb-arbitrage':{title:'MLB Arbitrage',description:'How cross-sportsbook differences can appear in MLB moneylines, run lines and totals.',body:['MLB markets include moneylines, run lines and totals, each of which can be priced differently across sportsbooks. Cross-book differences can occasionally create a mathematical arbitrage when all mutually exclusive outcomes are covered.','Baseball markets also change around starting-pitcher information and lineup confirmation. Settlement terms can differ when pitcher designations or market rules are involved, so market identity matters.'],points:['Verify starting-pitcher and action rules','Match run-line or total numbers exactly','Check quote freshness','Cover every outcome required by the market']},
 'nfl-arbitrage':{title:'NFL Arbitrage',description:'How NFL moneyline, spread and total prices can differ across sportsbooks.',body:['NFL books can disagree on moneyline prices, spreads and totals, particularly as information and market activity change. An arbitrage calculation must compare equivalent outcomes and account for the exact point line.','A price difference is not automatically an arbitrage. The complete set of mutually exclusive outcomes must produce an implied-probability sum below 100%.'],points:['Match spread and total numbers exactly','Compare current timestamps','Check push and settlement rules','Recalculate whenever either side moves']},
 'nba-arbitrage':{title:'NBA Arbitrage',description:'How fast-moving NBA prices can create temporary cross-sportsbook differences.',body:['NBA markets can move quickly across moneylines, spreads and totals. Temporary price dispersion across books is why freshness is essential to any arbitrage scanner.','The mathematical test remains the same: convert prices to implied probabilities and test the complete outcome set. Execution and settlement still determine whether a theoretical opportunity is usable.'],points:['Treat stale quotes as invalid','Match alternate lines carefully','Verify every required outcome','Recalculate on each confirmed update']},
 'nhl-arbitrage':{title:'NHL Arbitrage',description:'How NHL moneylines, puck lines and totals can differ across sportsbooks.',body:['NHL markets commonly include moneylines, puck lines and totals. Books can price these markets differently, creating cross-book dispersion and, occasionally, a mathematical arbitrage.','Overtime treatment and market settlement rules must match. Two prices that look complementary may not represent the same underlying outcome if their rules differ.'],points:['Check overtime and regulation-only terms','Match puck-line and total numbers','Verify quote freshness','Compare settlement rules before treating outcomes as complementary']},
 'market-research':{title:'InQsi Market Research',description:'Reproducible InQsi research based on aggregated sports-market observations.',body:['This section is reserved for research derived from InQsi market observations. We will publish a result only when its source window, sample size, inclusion rules and calculation can be stated clearly.','Until a study has passed that evidence threshold, InQsi will not manufacture statistics for search traffic. The research program is designed around reproducibility rather than headline claims.'],points:['State the observation window','Publish sample size and inclusion criteria','Separate descriptive findings from causal claims','Update or retract findings when the underlying evidence changes']}
};

export function generateStaticParams(){return Object.keys(guides).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
 const {slug}=await params; const g=guides[slug]; if(!g)return{};
 return{title:g.title,description:g.description,alternates:{canonical:`/learn/arbitrage/${slug}`},openGraph:{title:`${g.title} | InQsi`,description:g.description,type:'article'}};
}
export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const g=guides[slug]; if(!g)notFound();
 const schema={'@context':'https://schema.org','@type':'Article',headline:g.title,description:g.description,author:{'@type':'Organization',name:'InQsi'},publisher:{'@type':'Organization',name:'InQsi'},mainEntityOfPage:`https://inqsi.app/learn/arbitrage/${slug}`};
 return <main className="shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><article className="hero-card glass-card" style={{marginTop:24,maxWidth:920}}><p className="eyebrow blue">INQSI GUIDE</p><h1>{g.title}</h1><p className="hero-copy">{g.description}</p>{g.body.map((p,i)=><p className="hero-copy" key={i}>{p}</p>)}<h2>What to check</h2><ul>{g.points.map(x=><li key={x}>{x}</li>)}</ul><div className="hero-actions"><Link className="primary-button large" href="/arbitrage-v2">Open ARB Finder</Link><Link className="ghost-button large" href="/learn/arbitrage">Learning Center</Link></div></article></main>;
}
