'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
type Job={id:string;status:string;instruction:string;authorizedScope:string[];repository:string;startingRevision:string;branch?:string;changedFiles:string[];diff?:string;logs:string[];testResults:unknown[];commit?:string;pullRequest?:string;error?:string;updatedAt:string};
export function EngineeringConsole(){const [jobs,setJobs]=useState<Job[]>([]),[selected,setSelected]=useState<Job|null>(null),[instruction,setInstruction]=useState(''),[scope,setScope]=useState('frontend'),[message,setMessage]=useState('');
 const refresh=useCallback(async()=>{const r=await fetch('/api/engineering',{cache:'no-store'});if(r.status===503){setMessage('Secure administrator authentication or the engineering service is not configured.');return}if(!r.ok){setMessage('Access denied.');return}const data=await r.json();setJobs(data.jobs);if(selected){const current=data.jobs.find((j:Job)=>j.id===selected.id);if(current)setSelected(current)}},[selected?.id]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,3000);return()=>clearInterval(timer)},[refresh]);
 async function submit(e:FormEvent){e.preventDefault();const r=await fetch('/api/engineering',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({instruction,authorizedScope:scope.split(',').map(x=>x.trim()).filter(Boolean),startingRevision:'HEAD'})});const d=await r.json();if(r.ok){setInstruction('');setSelected(d.job);refresh()}else setMessage(d.error||'Submission failed')}
 async function action(name:'cancel'|'continue'){const body=name==='continue'?JSON.stringify({instruction}):undefined;const r=await fetch(`/api/engineering/${selected?.id}/${name}`,{method:'POST',headers:{'content-type':'application/json'},body});if(!r.ok)setMessage((await r.json()).error);else refresh()}
 return <main className="shell engineering-console"><header className="topbar"><div className="brand-block"><span className="brand-mark">Q</span><span><p className="eyebrow">InQsi private</p><h1>Engineering Console</h1></span></div><span className="api-badge">Admin · server verified</span></header><section className="engineering-grid"><section className="panel"><p className="eyebrow blue">New authorized task</p><h2>Direct the worker</h2><form onSubmit={submit}><label>Instructions<textarea required value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Describe the engineering change and acceptance checks…" /></label><label>Authorized paths (comma-separated)<input required value={scope} onChange={e=>setScope(e.target.value)} /></label><div className="scope-card"><b>KirtKurt/parlay-platform</b><span>Starting revision: repository HEAD</span><span>Deployment authority: none</span></div><button className="primary-button">Submit job</button></form>{message&&<p role="alert">{message}</p>}<h3>Durable history</h3><div className="job-list">{jobs.map(j=><button key={j.id} onClick={()=>setSelected(j)}><span className={`job-status ${j.status}`}>{j.status.replace('_',' ')}</span><b>{j.instruction}</b><small>{new Date(j.updatedAt).toLocaleString()}</small></button>)}</div></section><section className="panel result-panel">{selected?<><div className="inqsi-section-head"><div><p className="eyebrow blue">Job {selected.id.slice(0,8)}</p><h2>{selected.status.replace('_',' ')}</h2></div><span className={`job-status ${selected.status}`}>{selected.status}</span></div><div className="scope-card"><span>Repo: {selected.repository}</span><span>Base: <code>{selected.startingRevision}</code></span><span>Branch: {selected.branch||'pending'}</span></div><div className="job-actions"><button onClick={()=>action('cancel')} disabled={!['queued','running'].includes(selected.status)}>Cancel worker</button><button onClick={()=>action('continue')} disabled={!['completed','failed','blocked','awaiting_approval'].includes(selected.status)||!instruction}>Continue</button></div>{selected.error&&<p className="error">{selected.error}</p>}<h3>Progress</h3><pre>{selected.logs.join('\n')||'Waiting for real worker events…'}</pre><h3>Changed files</h3><ul>{selected.changedFiles.map(f=><li key={f}>{f}</li>)}</ul><h3>Diff</h3><pre>{selected.diff||'No recorded diff.'}</pre><h3>Tests</h3><pre>{selected.testResults.length?JSON.stringify(selected.testResults,null,2):'No test result reported.'}</pre>{selected.commit&&<p>Commit: {selected.commit}</p>}{selected.pullRequest&&<p>Pull request: {selected.pullRequest}</p>}</>:<div className="empty-state"><h2>Select a job</h2><p>Progress, sanitized logs, actual changes, tests, commit, and pull-request references appear here.</p></div>}</section></section></main>}
