import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';
import { loadPublicationPolicy, validatePublisherRequest, validatePullRequestIdentity, isPublishableScope, PROOF_ROOT, PROOF_CHECK } from '../src/publication-policy.js';
import { validatePublicationHistory, assertMainAncestor } from '../src/publication-git-guard.js';
import { sha256, writePublicationReceipt, readPublicationReceipt } from '../src/publication.js';
import { runWithPublisherLock } from '../src/publisher-lock.js';
import { JobStore } from '../src/store.js';
import { updateJobFromPublisher } from '../src/publisher-job-state.js';
import { loadConfig } from '../src/config.js';

const id='11111111-1111-4111-8111-111111111111';
const policyEnv={ INQSI_ENGINEERING_PUBLICATION_POLICY:'proof-v1', INQSI_ENGINEERING_ALLOWED_SCOPES:PROOF_ROOT, INQSI_ENGINEERING_REQUIRED_CHECKS:PROOF_CHECK };
const policy=loadPublicationPolicy(policyEnv);
const patch=`diff --git a/${PROOF_ROOT}/proof.md b/${PROOF_ROOT}/proof.md\n`;
const request=()=>({version:1,jobId:id,repository:'KirtKurt/parlay-platform',branch:`inqsi/publish-${id}`,startingRevision:'a'.repeat(40),authorizedScope:[PROOF_ROOT],changedFiles:[`${PROOF_ROOT}/proof.md`],requiredChecks:[PROOF_CHECK],patchSha256:sha256(patch)});
const temporary=(t)=>{ const dir=fs.mkdtempSync(path.join(os.tmpdir(),'inqsi-boundary-'));t.after(()=>fs.rmSync(dir,{force:true,recursive:true})); return dir; };
const git=(cwd,...args)=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
function repo(t){const dir=temporary(t);git(dir,'init','-b','main');git(dir,'config','user.name','Local test');git(dir,'config','user.email','test@example.invalid');fs.mkdirSync(path.join(dir,PROOF_ROOT));fs.writeFileSync(path.join(dir,PROOF_ROOT,'proof.md'),'Initial proof\n');git(dir,'add','.');git(dir,'commit','-m','main baseline');return dir;}
function commit(dir,file,contents){fs.mkdirSync(path.dirname(path.join(dir,file)),{recursive:true});fs.writeFileSync(path.join(dir,file),contents);git(dir,'add','.');git(dir,'commit','-m','test fixture');return git(dir,'rev-parse','HEAD');}
function candidate(t){const dir=repo(t),main=git(dir,'rev-parse','HEAD');git(dir,'checkout','-b','candidate');const head=commit(dir,`${PROOF_ROOT}/proof.md`,'Verified proof\n');const manifest={...request(),startingRevision:main};return {dir,main,head,manifest};}

for(const name of Object.keys(policyEnv)) test(`publisher requires explicit ${name}`,()=>{const env={...policyEnv};delete env[name];assert.throws(()=>loadPublicationPolicy(env));});
test('publisher accepts only the configured proof scope and exact check',()=>assert.equal(validatePublisherRequest(request(),patch,policy),true));
test('worker cannot replace check with build',()=>assert.throws(()=>validatePublisherRequest({...request(),requiredChecks:['build']},patch,policy),/check_policy/));
test('worker cannot widen authorized scope beyond independent publisher policy',()=>assert.throws(()=>validatePublisherRequest({...request(),authorizedScope:['frontend']},patch,policy)));
test('publisher rejects executable disguised as proof',()=>assert.throws(()=>validatePublisherRequest({...request(),changedFiles:[`${PROOF_ROOT}/execute.js`]},patch,policy),/file_not_authorized/));
test('publisher rejects duplicate changed-file entries',()=>assert.throws(()=>validatePublisherRequest({...request(),changedFiles:[`${PROOF_ROOT}/proof.md`,`${PROOF_ROOT}/proof.md`]},patch,policy),/file_limit/));
for(const scope of ['engineering_console','frontend','.github','hello_world','engineering_console_publication_proof/../frontend',`${PROOF_ROOT}/config.js`,`${PROOF_ROOT}/.env`,`${PROOF_ROOT}-lookalike`]) test(`early scope rejects ${scope}`,()=>assert.equal(isPublishableScope(scope),false));
test('proof scope and markdown file scope are accepted',()=>{assert.equal(isPublishableScope(PROOF_ROOT),true);assert.equal(isPublishableScope(`${PROOF_ROOT}/probe.md`),true);});
test('config no longer defaults to path-filtered build',()=>{const env={...policyEnv,INQSI_ENGINEERING_OIDC_ISSUER:'https://issuer.example.invalid',INQSI_ENGINEERING_OIDC_AUDIENCE:'engineering',INQSI_ENGINEERING_JWKS_URI:'https://issuer.example.invalid/jwks',INQSI_ENGINEERING_ADMIN_CLAIM:'admin',INQSI_ENGINEERING_REPOSITORY:'/srv/repo',INQSI_ENGINEERING_DATA_DIR:'/srv/data',INQSI_ENGINEERING_WORKSPACE_ROOT:'/srv/jobs',INQSI_ENGINEERING_ORIGIN:'https://console.example.invalid',INQSI_ENGINEERING_BIND_ADDRESS:'127.0.0.1'};assert.deepEqual(loadConfig(env).requiredChecks,[PROOF_CHECK]);delete env.INQSI_ENGINEERING_REQUIRED_CHECKS;assert.throws(()=>loadConfig(env),/missing/);});
function pr(manifest,head){return{number:10,state:'open',draft:false,head:{ref:manifest.branch,sha:head,repo:{full_name:manifest.repository}},base:{ref:'main',repo:{full_name:manifest.repository}}};}
test('exact PR identity accepted',()=>validatePullRequestIdentity(pr(request(),'b'.repeat(40)),request(),'b'.repeat(40)));
for(const field of ['sha','repository','base','draft'])test(`wrong PR ${field} rejected`,()=>{const m=request(),head='b'.repeat(40),p=pr(m,head);if(field==='sha')p.head.sha='c'.repeat(40);if(field==='repository')p.head.repo.full_name='other/fork';if(field==='base')p.base.ref='release';if(field==='draft')p.draft=true;assert.throws(()=>validatePullRequestIdentity(p,m,head),/identity/);});
test('real Git: exact single-parent safe proof validates',async t=>{const f=candidate(t);assert.deepEqual((await validatePublicationHistory(f.dir,f.manifest,f.head,f.main,policy)).files,[`${PROOF_ROOT}/proof.md`]);});
test('real Git: unrelated main advance does not contaminate proof',async t=>{const f=candidate(t);git(f.dir,'checkout','main');const newer=commit(f.dir,'unrelated.txt','Independent main change\n');await validatePublicationHistory(f.dir,f.manifest,f.head,newer,policy);});
test('real Git: off-main starting revision with hidden protected changes is rejected',async t=>{const dir=repo(t),main=git(dir,'rev-parse','HEAD');git(dir,'checkout','-b','feature');const start=commit(dir,'engineering_console/hidden.js','Hidden change\n');const head=commit(dir,`${PROOF_ROOT}/proof.md`,'Proof\n');await assert.rejects(validatePublicationHistory(dir,{...request(),startingRevision:start},head,main,policy),/start_not_on_main/);});
test('real Git: additional out-of-scope change absent from manifest is rejected',async t=>{const dir=repo(t),main=git(dir,'rev-parse','HEAD');git(dir,'checkout','-b','candidate');fs.writeFileSync(path.join(dir,PROOF_ROOT,'proof.md'),'Safe\n');const head=commit(dir,'frontend/package.json','{}\n');await assert.rejects(validatePublicationHistory(dir,{...request(),startingRevision:main},head,main,policy),/complete_diff_mismatch/);});
test('real Git: reused matching tree with unexpected parent is rejected',async t=>{const f=candidate(t);git(f.dir,'commit','--allow-empty','-m','Extra ancestry');const head=git(f.dir,'rev-parse','HEAD');await assert.rejects(validatePublicationHistory(f.dir,f.manifest,head,f.main,policy),/unexpected_parent/);});
test('real Git: symlink with markdown extension is rejected',async t=>{const dir=repo(t),main=git(dir,'rev-parse','HEAD');git(dir,'checkout','-b','candidate');fs.unlinkSync(path.join(dir,PROOF_ROOT,'proof.md'));fs.symlinkSync('/etc/passwd',path.join(dir,PROOF_ROOT,'proof.md'));git(dir,'add','.');git(dir,'commit','-m','Symlink fixture');await assert.rejects(validatePublicationHistory(dir,{...request(),startingRevision:main},git(dir,'rev-parse','HEAD'),main,policy),/file_mode/);});
test('real Git: executable markdown file is rejected',async t=>{const f=candidate(t);git(f.dir,'reset','--soft',f.main);fs.chmodSync(path.join(f.dir,PROOF_ROOT,'proof.md'),0o755);git(f.dir,'add','.');git(f.dir,'commit','-m','Executable fixture');await assert.rejects(validatePublicationHistory(f.dir,f.manifest,git(f.dir,'rev-parse','HEAD'),f.main,policy),/file_mode/);});
test('real Git: already merged head is verified against its original patch',async t=>{const f=candidate(t);git(f.dir,'checkout','main');git(f.dir,'merge','--no-ff','candidate','-m','Merge proof');await validatePublicationHistory(f.dir,f.manifest,f.head,git(f.dir,'rev-parse','HEAD'),policy,{alreadyMerged:true});});
test('invalid revision fails before git option interpretation',async t=>assert.rejects(assertMainAncestor(temporary(t),'--help','a'.repeat(40)),/invalid_publication_revision/));
test('late publisher failure cannot replace durable merged receipt',t=>{const dir=temporary(t);const original=writePublicationReceipt(dir,{jobId:id,state:'merged',mergeCommit:'b'.repeat(40)});const returned=writePublicationReceipt(dir,{jobId:id,state:'publisher_failed',reason:'late retry'});assert.deepEqual(returned,original);assert.deepEqual(readPublicationReceipt(dir,id),original);});
test('late job update cannot downgrade merged completion',t=>{const dir=temporary(t),store=new JobStore(dir),job=store.create({instruction:'Proof',authorizedScope:[PROOF_ROOT]},'owner','a'.repeat(40));updateJobFromPublisher(dir,{jobId:job.id,state:'merged',mergeCommit:'b'.repeat(40)});updateJobFromPublisher(dir,{jobId:job.id,state:'publisher_failed',reason:'late failure'});assert.equal(store.get(job.id).status,'completed');assert.equal(store.get(job.id).publicationState,'merged');});
async function ready(file){for(let i=0;i<100;i++){if(fs.existsSync(file))return;await delay(10);}throw new Error('lock fixture did not start');}
function holder(dir){const script=path.join(dir,'holder.mjs');fs.writeFileSync(script,"import fs from 'node:fs';fs.writeFileSync(process.argv[2],String(process.pid));setTimeout(()=>{},Number(process.argv[3]));\n");return script;}
test('real processes: overlapping publishers cannot both own recovered claims',async t=>{const dir=temporary(t),script=holder(dir),locks=path.join(dir,'locks'),mark=path.join(dir,'ready');const first=runWithPublisherLock(locks,script,{args:[mark,'150'],stdio:'ignore'});await ready(mark);assert.equal(await runWithPublisherLock(locks,script,{args:[path.join(dir,'second'),'1'],stdio:'ignore'}),75);assert.equal(fs.existsSync(path.join(dir,'second')),false);assert.equal(await first,0);assert.equal(await runWithPublisherLock(locks,script,{args:[path.join(dir,'third'),'1'],stdio:'ignore'}),0);});
test('real processes: crashed holder releases lock without stale-PID reclamation',async t=>{const dir=temporary(t),script=holder(dir),locks=path.join(dir,'locks'),mark=path.join(dir,'ready');const first=runWithPublisherLock(locks,script,{args:[mark,'10000'],stdio:'ignore'});const rejected=assert.rejects(first,/interrupted/);await ready(mark);process.kill(Number(fs.readFileSync(mark,'utf8')),'SIGKILL');await rejected;assert.equal(await runWithPublisherLock(locks,script,{args:[path.join(dir,'recovered'),'1'],stdio:'ignore'}),0);});
test('real processes: independent lock directories do not collide',async t=>{const dir=temporary(t),script=holder(dir),mark=path.join(dir,'ready');const first=runWithPublisherLock(path.join(dir,'one'),script,{args:[mark,'150'],stdio:'ignore'});await ready(mark);assert.equal(await runWithPublisherLock(path.join(dir,'two'),script,{args:[path.join(dir,'independent'),'1'],stdio:'ignore'}),0);assert.equal(await first,0);});
test('symlinked publisher lock directory fails closed',async t=>{const dir=temporary(t),actual=path.join(dir,'actual'),link=path.join(dir,'link');fs.mkdirSync(actual);fs.symlinkSync(actual,link);await assert.rejects(runWithPublisherLock(link,holder(dir),{stdio:'ignore'}),/symlink/);});
test('trusted proof CLI accepts genuine safe Git diff without executing candidate code',t=>{const f=candidate(t);const script=new URL('../scripts/check-publication-proof.mjs',import.meta.url);const output=execFileSync(process.execPath,[script.pathname,f.dir,f.main,f.head,`inqsi/publish-${id}`],{encoding:'utf8'});const result=JSON.parse(output);assert.equal(result.state,'passed');assert.equal(result.head,f.head);assert.equal(result.changedFileCount,1);});
test('trusted proof CLI rejects a non-publisher branch',t=>{const f=candidate(t);assert.throws(()=>execFileSync(process.execPath,[new URL('../scripts/check-publication-proof.mjs',import.meta.url).pathname,f.dir,f.main,f.head,'other-branch'],{stdio:'pipe'}));});
test('UI requires explicit scope rather than protected Console default',()=>{const ui=fs.readFileSync(new URL('../../frontend/components/EngineeringConsole.tsx',import.meta.url),'utf8');assert.match(ui,/\[scope, setScope\] = useState\(''\)/);assert.doesNotMatch(ui,/useState\('engineering_console'\)/);});
test('request route validates scope and main ancestry before queue admission',()=>{const source=fs.readFileSync(new URL('../src/server.js',import.meta.url),'utf8');assert.match(source,/!isPublishableScope\(scope\)/);assert.ok(source.indexOf('await assertMainAncestor')<source.indexOf('const job = store.create'));});
