"""Operating report. Visibility, not a permission request."""
from __future__ import annotations

from stack2mlb import VERSION
from stack2mlb.backlog import BACKLOG, next_item
from stack2mlb.experiments import REGISTRY


def report(*, champion="KS1-LGB+dual-Poisson", date="2026-09-11") -> dict:
    nxt = next_item()
    rejected = [e.experiment_id for e in REGISTRY if e.promotion_decision == "reject"]
    shadow = [e.experiment_id for e in REGISTRY if e.promotion_decision == "shadow_only"]
    return {
        "system_health": "KS1 hourly research ingestion is the production loop. 2stackMLB is shadow-only.",
        "date": date,
        "champion_model": champion,
        "challenger_models": [VERSION],
        "todays_mlb_predictions": "Generated by ks1.daily on main; 2stackMLB sidecar is not in that job yet.",
        "locked_picks": "KS1 T-10 locks. Official field remains p_home.",
        "pending_predictions": "All Preview games before T-10 on the current ET slate.",
        "completed_grading": "ks1.nightly at 01:00 ET on the existing hourly workflow.",
        "model_performance": "Do not quote a cherry-picked subset. Read graded_ledger official_metrics.",
        "new_experiments": [e.as_dict() for e in REGISTRY],
        "recently_accepted_features": [],
        "recently_rejected_features": rejected,
        "shadow_experiments": shadow,
        "data_problems": [
            "Confirmed batting orders often empty in live feed (Phase 5 proof).",
            "Starter features are team_starter_prior, not the named pitcher.",
            "Park/weather omitted from accepted Poisson.",
            "Statcast research object exists and is unused.",
        ],
        "model_problems": [
            "LGB can print 77 when Poisson and market sit near 55.",
            "Independent Poisson ignores sequencing and extras.",
        ],
        "aws_infrastructure_problems": [
            "2stackMLB is not scheduled. Shadow attach is local/CLI only.",
            "Do not dispatch the main ingestion workflow from a research branch; it publishes.",
        ],
        "repairs_performed": [
            "2stackMLB engines + gate + live attach + Elo-from-grades + shadow persist.",
            "Experiment registry, backlog, walk-forward harness, failure taxonomy.",
        ],
        "current_biggest_bottleneck": nxt.as_dict(),
        "next_autonomous_action": (
            "Run walk-forward on the next available graded_ledger + locked rows. "
            "Do not promote. Do not refit KS1."
        ),
        "research_backlog": [i.as_dict() for i in BACKLOG],
        "promoted": False,
    }
