// Generated by .github/workflows/sync-vercel-arb-endpoint.yml.
// Public API Gateway endpoints only; never place secrets in this file.
export const GENERATED_ARB_API_URL = "https://5g9tvven72.execute-api.us-east-1.amazonaws.com/Prod";
export const GENERATED_ARB_WEBSOCKET_URL = "wss://kb64d70kla.execute-api.us-east-1.amazonaws.com/Prod";
