// Generated by .github/workflows/sync-vercel-arb-endpoint.yml.
// Public API Gateway base URL only; never place secrets in this file.
export const GENERATED_ARB_API_URL = "https://5g9tvven72.execute-api.us-east-1.amazonaws.com/Prod";
