from pathlib import Path

path = Path('work/tennis_lock_handler.py')
s = path.read_text()

assert 'INQSI-TENNIS-PER-MATCH-LOCK-v5-tminus45-no-rescore' in s
s = s.replace('INQSI-TENNIS-PER-MATCH-LOCK-v5-tminus45-no-rescore','INQSI-TENNIS-PER-MATCH-LOCK-v5.2-tminus45-no-rescore-keyed-reads',1)

s = s.replace(
'''        self.archive = archive\n\n    def _pulls_and_manifest''',
'''        self.archive = archive\n        self._snapshot_cache: Dict[str, Dict[str, Dict[str, Any]]] = {}\n        self._pregame_cache: Dict[str, Dict[str, List[Dict[str, Any]]]] = {}\n\n    def _prepare_snapshot_cache(self, slate_date: str) -> None:\n        if slate_date in self._snapshot_cache:\n            return\n        rows = self.store.query_items("snapshots", lock_pk(slate_date), limit=10000, ascending=True)\n        self._snapshot_cache[slate_date] = {str(r.get("SK") or ""): copy.deepcopy(r) for r in rows if r.get("SK")}\n\n    def _snapshot_item(self, slate_date: str, sk: str) -> Optional[Dict[str, Any]]:\n        self._prepare_snapshot_cache(slate_date)\n        item = self._snapshot_cache[slate_date].get(str(sk))\n        return copy.deepcopy(item) if item is not None else None\n\n    def _remember_snapshot(self, slate_date: str, item: Optional[Dict[str, Any]]) -> None:\n        if item and slate_date in self._snapshot_cache and item.get("SK"):\n            self._snapshot_cache[slate_date][str(item["SK"])] = copy.deepcopy(item)\n\n    def _pulls_and_manifest''',1)

start = s.index('    def _get_lock(')
end = s.index('    def _eligible_candidate(', start)
replacement = '''    def _get_lock(self, slate_date: str, identity: str) -> Optional[Dict[str, Any]]:\n        return self._snapshot_item(slate_date, canonical_lock_sk(identity))\n\n    def _get_outcome(self, slate_date: str, identity: str) -> Optional[Dict[str, Any]]:\n        return self._snapshot_item(slate_date, lock_outcome_sk(identity))\n\n    def _pregame_rows(self, slate_date: str, match: Dict[str, Any]) -> List[Dict[str, Any]]:\n        identity = event_identity(match)\n        cache = self._pregame_cache.setdefault(slate_date, {})\n        if identity in cache:\n            return copy.deepcopy(cache[identity])\n        prefix = f"PREGAME#MATCH#{identity}#"\n        rows: List[Dict[str, Any]] = []\n        if hasattr(self.store, "_table"):\n            from boto3.dynamodb.conditions import Key\n            table = self.store._table("predictions")\n            last = None\n            while True:\n                kwargs: Dict[str, Any] = {\n                    "KeyConditionExpression": Key("PK").eq(pregame_prediction_pk(slate_date)) & Key("SK").begins_with(prefix),\n                    "ScanIndexForward": True,\n                    "Limit": 250,\n                }\n                if last:\n                    kwargs["ExclusiveStartKey"] = last\n                response = table.query(**kwargs)\n                rows.extend(response.get("Items") or [])\n                last = response.get("LastEvaluatedKey")\n                if not last or len(rows) >= 1000:\n                    break\n        else:\n            rows = [r for r in self.store.query_items("predictions", pregame_prediction_pk(slate_date), limit=10000, ascending=True) if str(r.get("SK") or "").startswith(prefix)]\n        selected: List[Dict[str, Any]] = []\n        for item in rows:\n            if item.get("record_type") != PREGAME_RECORD_TYPE or item.get("sport") != "tennis":\n                continue\n            if str(item.get("match_identity") or "") != identity:\n                continue\n            data = copy.deepcopy(item.get("data") or {})\n            if not isinstance(data, dict):\n                continue\n            if str(data.get("matchIdentity") or data.get("gameIdentity") or "") != identity:\n                continue\n            if canonical_fingerprint(data) != str(item.get("prediction_payload_fingerprint") or ""):\n                continue\n            data["_pregame_pk"] = item.get("PK")\n            data["_pregame_sk"] = item.get("SK")\n            data["_pregame_fingerprint"] = item.get("prediction_payload_fingerprint")\n            selected.append(data)\n        selected.sort(key=_candidate_sort_key)\n        cache[identity] = copy.deepcopy(selected)\n        return selected\n\n'''
s = s[:start] + replacement + s[end:]

s = s.replace('existing = self.store.get_item("snapshots", lock_pk(slate_date), readiness_sk(identity, minutes))','existing = self._snapshot_item(slate_date, readiness_sk(identity, minutes))')
s = s.replace('existing = self.store.get_item("snapshots", lock_pk(slate_date), key)','existing = self._snapshot_item(slate_date, key)')

s = s.replace('return self.store.put_item("snapshots", item, if_absent=True).get("item") or item','stored = self.store.put_item("snapshots", item, if_absent=True).get("item") or item\n        self._remember_snapshot(slate_date, stored)\n        return stored',3)
s = s.replace('        stored = write.get("item") or item\n','        stored = write.get("item") or item\n        self._remember_snapshot(slate_date, stored)\n',1)
s = s.replace('        results = [\n            self.run_match(slate_date, match, now=current, force=force) for match in matches\n        ]','        self._prepare_snapshot_cache(slate_date)\n        results = [\n            self.run_match(slate_date, match, now=current, force=force) for match in matches\n        ]',1)
s = s.replace('        pulls, matches, manifest = self._pulls_and_manifest(slate_date)\n        rows: List[Dict[str, Any]] = []','        pulls, matches, manifest = self._pulls_and_manifest(slate_date)\n        self._prepare_snapshot_cache(slate_date)\n        rows: List[Dict[str, Any]] = []',1)
s = s.replace('self.store.get_item(\n                    "snapshots", lock_pk(slate_date), readiness_sk(identity, minutes)\n                )','self._snapshot_item(slate_date, readiness_sk(identity, minutes))')
s = s.replace('self.store.get_item(\n                    "snapshots", lock_pk(slate_date), release_sk(identity, minutes)\n                )','self._snapshot_item(slate_date, release_sk(identity, minutes))')

path.write_text(s)
print('patched', len(s))
